### ISSUE TITLE
workers.api.error.script_too_large error on cloudflare deploy

### ISSUE THREAD

**Issue by husayt** [Atinux/atinotes#10]
Tried to deploy on cloudfalre and got the above error:

https://community.cloudflare.com/t/paid-plan-failed-to-publish-your-function-got-error-your-functions-script-is-over-the-1-mib-size-limit-workers-api-error-script-too-large/597797

They recommend to bring the size of function to under 1mb

**Comment by Atinux** [comment]
Indeed for this template we need to have a Workers Paid plan.

Will update it as suggested in https://github.com/nuxt-hub/feedback/issues/13
