### ISSUE TITLE
Unable to preview without buying $250 license

### ISSUE THREAD

**Issue by yieme** [Atinux/atinotes#14]
`npm run preview` requires `npm run build` which requires purchasing a PRO UI license. Makes it difficult to kick the tires unless you fork out $250 for a license.

**Comment by Atinux** [comment]
Indeed I am based on Nuxt UI Pro for it. Note that with UI Pro you can also use [those templates](https://ui.nuxt.com/pro/templates).

BTW this is free when running `npm run dev`
