### ISSUE TITLE
`nuxt-og-image` is not work?

### ISSUE THREAD

**Issue by linpengteng** [Atinux/atinotes#15]
```ts
  defineOgImageComponent('OgImagePage', {
    title: page.value.parsed.data?.title || 'Missing title',
    description: page.value.parsed.data?.description || 'Missing description'
  })
```

<img width="1888" alt="image" src="https://github.com/user-attachments/assets/23284873-0e3f-48fc-9a95-8cd38f4325e5">

**Comment by Atinux** [comment]
It works for me:
![CleanShot 2024-07-29 at 18 16 36@2x](https://github.com/user-attachments/assets/71a36708-6464-4d05-b485-2bce1e0a9b0d)

Try again, I updated the dependencies

**Comment by linpengteng** [comment]
working, thanks
