### ISSUE TITLE
custom useFetch has type bug

### ISSUE THREAD

**Issue by kingyue737** [Atinux/atinotes#6]
Reproduction: https://stackblitz.com/edit/atinotes-1

Thanks for sharing the way to make a custom `useFetch`. But I found some type bugs with `useAPI`:

1. When I set a default value in fetch options, it will raise error:

```
error TS2322: Type '() => never[]' is not assignable to type '() => Ref<null> | null'.
  Type 'never[]' is missing the following properties from type 'Ref<null>': value, [RefSymbol]
```

2. With a non-null default value, `useAPI` still returns a nullable data:

```
error TS18047: 'data2.value' is possibly 'null'
```

Original `useFetch` has no such issue.

**Comment by manniL** [comment]
Seems reasonable to send a PR ;)

**Comment by aaharu** [comment]
Here is a workaround!
```ts
function useAPI<T>(
  url: string | (() => string),
  options: Omit<UseFetchOptions<T>, 'default'> & { default: () => T | Ref<T> },
) {
  return useFetch(url, {
    ...options,
  })
}
const { data: data2 } = useAPI<{ bug: string }[]>('/', {
  default: () => [],
})
data2.value.push({ bug: 'bug' })
```

The `useFetch` returns data null if the `default` option is undefined, so the error can be resolved by making `default` required in the options of the `useAPI`.

**Comment by Atinux** [comment]
Updated in the article thank you!
